version: '3.7'

services:
  php:
    build: ./docker/php
    container_name: scanup-php
    restart: on-failure

  db:
    image: postgres
    container_name: scanup-db
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  web:
    build: ./docker/nginx
    container_name: scanup-nginx
    restart: on-failure
    depends_on:
      - php
      - db

  adminer:
    image: adminer
    container_name: scanup-adminer
    restart: on-failure
    ports:
      - 8080:8080